config/routes.rb
Rails.application.routes.draw do
  get 'library/index'

  resources :providers
  resources :product_merceria
  root to: 'application#dashboard'
  resources :retaceria
  resources :colors
  resources :categories
  resources :roles
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions',passwords: 'users/passwords' }

  scope '/admin' do
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, uniqueness: true,
            presence: { message: "Es necesario el nombre de la categoría" }
  has_many :retaceriums

  def self.active
    Category.where(is_delete: false).order(name: :asc)
  end
end

app/models/color.rb
class Color < ApplicationRecord
  validates :name, uniqueness: true, presence: {message: "Es necesario el nombre del color"}
  has_many :has_colors
  has_many :retaceriums, through: :has_colors
  def self.active
    Color.where(is_delete: false).order(name: :asc)
  end
end

app/models/has_color.rb
class HasColor < ApplicationRecord
  belongs_to :retacerium
  belongs_to :color
end

app/models/has_product.rb
class HasProduct < ApplicationRecord
  belongs_to :provider
  belongs_to :product_mercerium
end

app/models/product_mercerium.rb
class ProductMercerium < ApplicationRecord
  validates :article, uniqueness: true
end

app/models/provider.rb
class Provider < ApplicationRecord
  has_many :has_products
  has_many :product_merceriums, through: :has_products
  validates :name, presence: { message: "Es necesario el nombre del proveedor" }
  validates :razon, presence: { message: "Es necesario la razon del proveedor" }
  validates :phone,presence: false, allow_blank: true, numericality: { only_integer: true , message: "El teléfono debe tener solo números"}
  validates :cuit,presence: false,  allow_blank: true,numericality: { only_integer: true , message: "El CUIT debe tener solo números"}
  validates :email,presence: false,  allow_blank: true,format: { :with => Devise::email_regexp, message: "El correo no tiene el formato correcto" }

  def self.active
    Provider.where(is_delete: false).order(razon: :asc)
  end
end

app/models/retacerium.rb
class Retacerium < ApplicationRecord
  validates :name, presence: {message: "Es necesario el nombre del producto"}
  validates :cost, presence: {message: "Es necesario el campo Costo"}
  validates :rinde, presence: {message: "Es necesario el campo Rinde"}

  belongs_to :category
  has_many :has_colors
  has_many :colors, through: :has_colors
  after_create :save_colors
  after_update :update_colors

  def arraycolors=(value)
    @colors = value || []
  end

  def update_colors
    if @colors.any?
      has_colors = HasColor.where("retacerium_id = ?", self.id)
      has_colors.each do |item|
        item.destroy
      end

      @colors.each do |color_id|
        HasColor.create(color_id: color_id, retacerium_id: self.id)
      end
    end

  end


  private

  def save_colors
    # raise @categories.to_yaml
    if !@colors.nil?
      @colors.each do |color_id|
        HasColor.create(color_id: color_id, retacerium_id: self.id)
      end
    end
  end

end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :role
  validates :email, uniqueness: true
  validates :username, uniqueness: true, length: {minimum: 5}

  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  before_create do
    self.key = 1234 if is_sale_retaceria?
  end

  def email_changed?
    false
  end

  def is_administrador?
    self.role_id==1
  end

  def is_sale_retaceria?
    self.role_id==2
  end
  def is_caja_retaceria?
    self.role_id==3
  end
  def is_sale_merceria?
    self.role_id==4
  end
  def is_caja_merceria?
    self.role_id==5
  end




end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  before_action :autheticate_administrator!

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_roles, :autheticate_administrator!
  layout 'dashboard'
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @title = 'Nuevo usuario'
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params.to_h.merge(password: params[:user][:username]))
    respond_to do |format|
      if @user.save
        format.html {redirect_to @user,:flash => {success: 'Usuario creado exitosamente'}}
        format.json {render :show, status: :created, location: @user}
      else
        format.html {render :new,:flash => {error: 'Error al editar el usuario'}}
        format.json {render json: @user.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html {redirect_to @user, :flash => {success: 'Usuario editado exitosamente'} }
        format.json {render :show, status: :ok, location: @user}
      else
        format.html {render :edit}
        format.json {render json: @user.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html {redirect_to users_url, :flash => {success: 'Usuario eliminado exitosamente'} }
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :phone, :email, :username, :role_id)
  end

  def set_roles
    @roles = Role.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def content_header(isBack,pathBack)
    if user.avatar?
      image_tag user.avatar.url(:avatar), class: cl,id:cl
    else
      # image_tag "default/default-avatar.png", id:cl, class:cl, width: '100%', height: '100%'
      image_tag user.avatar.default_url, id:cl, class:cl, width: '100%', height: '100%'

    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/retaceria_helper.rb
module RetaceriaHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/partials/_content_header.html.erb
<section class="content-header">

  <div class=" back" style="display: inline-block">
    <% if back %>
        <a href="<%= backPath %>"><i class="fa fa-arrow-left fa-2x" aria-hidden="true"></i></a>
    <% end %>
  </div>
  <h1 class="mt-0">
    <%= title %>
  </h1>
  <% if add==1 %>
      <%= link_to text.html_safe, path_action , class: 'btn btn-default pull-right' %>
  <% end %>
  <% if add==0 %>
      <%= link_to '', path_action, class: 'fa fa-trash pull-right fa-2x', method: :delete, data: {confirm: "¿Esta seguro que desea eliminar #{item}?"} %>
  <% end %>

</section>

app/views/partials/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 2.4.0
  </div>
  <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
  reserved.
</footer>

app/views/partials/_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <a href="<%= root_path %>" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>A</b>LT</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg">Administración</span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- Messages: style can be found in dropdown.less-->
        <li class="dropdown messages-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-envelope-o"></i>
            <span class="label label-success">4</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 4 messages</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu">
                <li><!-- start message -->
                  <a href="#">
                    <div class="pull-left">
                      <img src="<%= image_url 'user2-160x160.jpg' %>" class="img-circle" alt="User Image">
                    </div>
                    <h4>
                      Support Team
                      <small><i class="fa fa-clock-o"></i> 5 mins</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
                <!-- end message -->
              </ul>
            </li>
            <li class="footer"><a href="#">See All Messages</a></li>
          </ul>
        </li>
        <!-- Notifications: style can be found in dropdown.less -->
        <li class="dropdown notifications-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-bell-o"></i>
            <span class="label label-warning">10</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 10 notifications</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu">
                <li>
                  <a href="#">
                    <i class="fa fa-users text-aqua"></i> 5 new members joined today
                  </a>
                </li>
              </ul>
            </li>
            <li class="footer"><a href="#">View all</a></li>
          </ul>
        </li>
        <!-- Tasks: style can be found in dropdown.less -->
        <li class="dropdown tasks-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-flag-o"></i>
            <span class="label label-danger">9</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 9 tasks</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu">
                <li><!-- Task item -->
                  <a href="#">
                    <h3>
                      Design some buttons
                      <small class="pull-right">20%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">20% Complete</span>
                      </div>
                    </div>
                  </a>
                </li>
                <!-- end task item -->
              </ul>
            </li>
            <li class="footer">
              <a href="#">View all tasks</a>
            </li>
          </ul>
        </li>
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img src="<%= image_url 'user2-160x160.jpg' %>" class="user-image" alt="User Image">
            <span class="hidden-xs"><%= current_user.username %></span>
          </a>
          <ul class="dropdown-menu">
            <li class="user-header">
              <img src="<%= image_url 'user2-160x160.jpg' %>" class="img-circle">
              <p>
                <%= current_user.name %>
              </p>
            </li>
            <% if user_signed_in? %>
                <li class="user-footer">
                  <div class="pull-left">
                    <a href="#" class="btn btn-default btn-flat">Profile</a>

                  </div>
                  <div class="pull-right">
                    <%= link_to('Salir', destroy_user_session_path, :method => :delete, class: 'btn btn-default btn-flat') %>
                  </div>
            <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/partials/_sidebar.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <% if current_user.is_administrador? %>
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
          <li class="active"><a href="#retaceria-tab" data-toggle="tab">Retaceria</a></li>
          <li><a href="#merceria-tab" data-toggle="tab">Merceria</a></li>
        </ul>
    <% end %>

    <div class="tab-content">
      <div class="tab-pane active" id="retaceria-tab">
        <ul class="sidebar-menu" data-widget="tree">
          <li>
            <a href="<%= retaceria_path %>">
              <span>Productos</span>
            </a>
          </li>
          <li>
            <a href="#">
              <span>Ventas</span>
            </a>
          </li>
          <li>
            <a href="#">
              <span>Estadísticas</span>
            </a>
          </li>
        </ul>
      </div>
      <div class="tab-pane" id="merceria-tab">
        <ul class="sidebar-menu" data-widget="tree">
          <li>
            <a href="<%= product_merceria_path %>">
              <span>Productos</span>
            </a>
          </li>
          <li>
            <a href="#">
              <span>Ventas</span>
            </a>
          </li>
          <li>
            <a href="#">
              <span>Estadísticas</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <% if current_user.is_administrador? %>
        <ul class="sidebar-menu" data-widget="tree">
          <li>
            <a href="<%= users_path %>">
              <span>Usuarios</span>
            </a>
          </li>
          <li>
            <a href="<%= library_index_path %>">
              <span>Libreria</span>
            </a>
          </li>
          <li>
            <a href="<%= providers_path %>">
              <span>Proveedores</span>
            </a>
          </li>
        </ul>
    <% end %>
  </section>
  <!-- /.sidebar -->
</aside>