config/routes.rb
Rails.application.routes.draw do
  get 'library/index'

  resources :providers
  resources :product_merceria
  root to: 'application#dashboard'
  resources :retaceria
  resources :colors
  resources :categories
  resources :roles
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions',passwords: 'users/passwords' }

  scope '/admin' do
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :role
  validates :email, uniqueness: true
  validates :username, uniqueness: true, length: {minimum: 5}

  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  before_create do
    self.key = 1234 if is_sale_retaceria?
  end

  def email_changed?
    false
  end

  def is_administrador?
    self.role_id==1
  end

  def is_sale_retaceria?
    self.role_id==2
  end
  def is_caja_retaceria?
    self.role_id==3
  end
  def is_sale_merceria?
    self.role_id==4
  end
  def is_caja_merceria?
    self.role_id==5
  end




end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  layout 'custom_devise'

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      respond_with({}, location: after_sending_reset_password_instructions_path_for(resource_name))
    else
      @error=true
      respond_with(resource)
    end
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  layout 'custom_devise', only: [:new]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  layout 'custom_devise', only: [:new]

  # GET /resource/sign_in
  def new
    # render  layout: 'dashboard'
    super
  end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:success, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_roles, :autheticate_administrator!
  layout 'dashboard'
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @title = 'Nuevo usuario'
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params.to_h.merge(password: params[:user][:username]))
    respond_to do |format|
      if @user.save
        format.html {redirect_to @user,:flash => {success: 'Usuario creado exitosamente'}}
        format.json {render :show, status: :created, location: @user}
      else
        format.html {render :new,:flash => {error: 'Error al editar el usuario'}}
        format.json {render json: @user.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html {redirect_to @user, :flash => {success: 'Usuario editado exitosamente'} }
        format.json {render :show, status: :ok, location: @user}
      else
        format.html {render :edit}
        format.json {render json: @user.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html {redirect_to users_url, :flash => {success: 'Usuario eliminado exitosamente'} }
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :phone, :email, :username, :role_id)
  end

  def set_roles
    @roles = Role.all
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="box">
  <%= form_with(model: user, local: true, html: {class: 'form-horizontal', autocomplete: 'off'}) do |form| %>
      <div class="box-body">

        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= form.label :name, 'Nombre y apellidos', class: 'col-sm-4 control-label ta-left' %>
              <div class="col-sm-8">
                <%= form.text_field :name, id: :name, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <%= form.label :phone, 'Teléfono', class: 'col-sm-2 control-label ta-left' %>
              <div class="col-sm-10">
                <%= form.text_field :phone, id: :phone, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <%= form.label :email, 'Correo', class: 'col-sm-2 control-label ta-left' %>
              <div class="col-sm-10">
                <%= form.text_field :email, id: :email, class: 'form-control' %>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <%= form.label :username, 'Usuario', class: 'col-sm-2 control-label ta-left' %>
              <div class="col-sm-10">
                <%= form.text_field :username, id: :username, class: 'form-control' %>
              </div>
              <br>
            </div>
            <p class="small"><i>Para el 1er acceso la contraseña será igual que el usuario</i></p>


            <%= form.hidden_field :password, id: :password, value: 'pas' %>

            <div class="form-group">
              <%= form.label :role_id, 'Rol', class: 'col-sm-2 control-label ta-left' %>
              <div class="col-sm-10">
                <select name="user[role_id]" id="role_id" class="form-control">
                  <% if action_name == "edit" %>
                      <% @roles.each do |rol| %>
                          <option  <%= 'selected' if rol.id == user.role.id %> value="<%= rol.id %>"><%= rol.name %></option>
                      <% end %>

                  <% else %>
                      <option selected></option>
                      <% @roles.each do |rol| %>
                          <option value="<%= rol.id %>"><%= rol.name %></option>
                      <% end %>
                  <% end %>
                </select>
              </div>
            </div>
            <p class="small"><i>Para el 1er acceso el código será 1234</i></p>
          </div>
          <div class="col-md-12">
            <div class="actions">
              <%= form.submit 'Guardar', class: 'btn btn-default pull-right' %>
            </div>
          </div>
        </div>
      </div>
  <% end %>
</div>

<% content_for :otherscripts do %>

    <% if user.errors.any? %>
        <script>
            <% user.errors.full_messages.each do |err| %>
                toastr.error('<%= err %>');
            <% end %>
        </script>
    <% end %>

<% end %>

app/views/users/edit.html.erb
<%= render 'partials/content_header', back: true, backPath: users_path, title: '', add: 2, text: '', path_action: '' %>
<section class="content">
<%= render 'form', user: @user %>
</section>

app/views/users/index.html.erb
<%= render 'partials/content_header', back: false,backPath:'' ,title: @title,add:1,text:'<i class="fa fa-plus"></i> Nuevo usuario',path_action: new_user_path %>
<section class="content">
  <div class="box">
    <!-- /.box-header -->
    <div class="box-body table-responsive">
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Usuario</th>
          <th>Rol</th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.username %></td>
            <td><%= user.role.name %></td>
            <td class="width-50"><%= link_to '', user, class: 'fa fa-eye' %></td>
            <td class="width-50"><%= link_to '', edit_user_path(user), class: 'fa fa-pencil' %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <!-- /.box-body -->
  </div>
</section>

app/views/users/new.html.erb
<%= render 'partials/content_header', back: true,backPath:users_path ,title: @title,add:2,text:'',path_action: '' %>
<section class="content">
<%= render 'form', user: @user, roles: @roles %>
</section>

app/views/users/show.html.erb
<%= render 'partials/content_header', back: true, backPath: users_path, title: '', add: 0, text: '', path_action: @user, item: 'el usuario' %>
<section class="content">
  <div class="box">
    <div class="box-body">
      <br>
      <div class="row form-horizontal">
        <div class="col-md-6">
          <div class="form-group">
            <div class="show-property">
              <label>
                <span class="show-key">Nombre y apellido:</span>
                <span class="show-value" style="left:35%;"><%= @user.name %></span>
              </label>
            </div>
          </div>

          <div class="form-group">
            <div class="show-property">
              <label>
                <span class="show-key">Télefono:</span>
                <span class="show-value" style="left:35%;"><%= @user.phone %></span>
              </label>
            </div>
          </div>
          <div class="form-group">
            <div class="show-property">
              <label>
                <span class="show-key">Correo:</span>
                <span class="show-value" style="left:35%;"><%= @user.email %></span>
              </label>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <div class="show-property">
              <label>
                <span class="show-key">Usuario:</span>
                <span class="show-value"><%= @user.username %></span>
              </label>
            </div>
          </div>
          <div class="form-group">
            <div class="show-property">
              <label>
                <span class="show-key">Rol:</span>
                <span class="show-value"><%= @user.role.name %></span>
              </label>
            </div>
          </div>
          <div class="form-group">
            <div class="show-property">
              <label>
                <span class="show-key">Creación:</span>
                <span class="show-value"><%= @user.created_at.strftime("%m/%d/%Y")%></span>
              </label>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /.box-body -->
  </div>
</section>