config/routes.rb
Rails.application.routes.draw do
  get 'library/index'

  resources :providers
  resources :product_merceria
  root to: 'application#dashboard'
  resources :retaceria
  resources :colors
  resources :categories
  resources :roles
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions',passwords: 'users/passwords' }

  scope '/admin' do
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, uniqueness: true,
            presence: { message: "Es necesario el nombre de la categoría" }
  has_many :retaceriums

  def self.active
    Category.where(is_delete: false).order(name: :asc)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  layout 'dashboard'
  before_action :autheticate_administrator!

  # GET /categories
  # GET /categories.json
  def index
    @title = 'Categorias de Productos'
    # @categories = Category.all.order(name: :asc)
    respond_to do |format|
      format.html
      format.json { render json: CategoryDatatable.new(params, view_context: view_context) }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @title = 'Nueva catgoria'
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category ,:flash => {success: 'Categoría creada exitosamente'}}
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new,:flash => {error: 'Error al crear la categoria '}}
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)

        format.html { redirect_to categories_path, :flash => {success: 'Categoría editada exitosamente'} }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.js {render :edit}
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    if @category.retaceriums.any?
       @category.is_delete = true
       @category.save
    else
      @category.destroy
    end
    respond_to do |format|
      format.html { redirect_to categories_url, :flash => {success: 'Categoría eliminada exitosamente'} }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_edit_r.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_with(model: @category,html: { style: "display:inline;",autocomplete: "off" }) do |f| %>
        <div class="modal-body">
          <ul class="errors"></ul>

          <div class="form-group">
            <%= f.label :name ,'Categoria', class:"control-label" %>
            <%= f.text_field :name, class: "form-control" %>
          </div>

        </div>
        <div class="modal-footer">
          <%= f.submit 'Guardar', class: "btn btn-primary" ,data: { "disable-with": "Guardando..." } %>
          <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
        </div>
    <% end %>
  </div>
</div>

app/views/categories/_form.html.erb
<div class="box">
  <%= form_with(model: category, local: true, :html => {autocomplete: "off"}) do |form| %>
      <div class="box-body">

        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= form.label :name, 'Título', class: 'col-sm-4 control-label ta-left' %>
              <%= form.text_field :name, id: :category_name, class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-12">
            <div class="actions">
              <%= form.submit 'Guardar', class: 'btn btn-default' %>
            </div>
          </div>
        </div>
      </div>
  <% end %>

  <% content_for :otherscripts do %>

      <% if category.errors.any? %>
          <script>
              <% category.errors.full_messages.each do |err| %>
              toastr.error('<%= err %>');
              <% end %>
          </script>
      <% end %>

  <% end %>
</div>

app/views/categories/_index_r.html.erb
<% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td style="width: 50px"><%= link_to '', edit_category_path(category),remote: true, class: 'fa fa-pencil' %></td>
      <td style="width: 50px"><%= link_to '', category, class: 'fa fa-trash', method: :delete, data: {confirm: '¿Está usted seguro que desea eliminar la categoría?'} %></td>
    </tr>
<% end %>

app/views/categories/edit.html.erb
<%= render 'partials/content_header', back: true, backPath: categories_path, title: '', add: 2, text: '', path_action: '' %>
<section class="content">
  <%= render 'form', category: @category %>
</section>

app/views/categories/edit.js.erb
$( document ).ready(function() {
console.log('ready');
});
$("#product-modal").html("<%= escape_javascript(render 'edit_r') %>")
$("#product-modal").modal("show");

<% if @category.errors.any? %>

<% @category.errors.full_messages.each do |err| %>
toastr.options.closeButton = true;
toastr.error('<%= err %>');
<% end %>

<% end %>

app/views/categories/index.html.erb
<%= render 'partials/content_header', back: true,backPath:library_index_path ,title: @title,add:1,text:'Nueva categoría',path_action: new_category_path %>
<section class="content">
  <div class="box">
    <!-- /.box-header -->
    <div class="box-body table-responsive">
      <table id="dttb" class="table responsive nowrap table-hover" data-source="<%= categories_path(format: :json) %>">
        <thead>
        <tr>
          <td>Categoria</td>
          <td></td>
          <td></td>
        </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>
    <div id="product-modal" class="modal fade"></div>
    <!-- /.box-body -->
  </div>
</section>


<% content_for :otherscripts do %>

    <script>
        $(document).ready(function() {
            $('#dttb').dataTable({
                "processing": true,
                "serverSide": true,
                "ajax": $('#dttb').data('source'),
                "pagingType": "full_numbers",
                "columns": [
                    {"data": "name"},
                    {"data": "edit_action","width":50},
                    {"data": "delete_action","width":50}
                ],
                "language": {
                    "lengthMenu": "Mostrar en bloques de  _MENU_  registros",
                    "zeroRecords": "No se he encontrado",
                    "info": "Mostrando página _PAGE_  de _PAGES_ pagina(s)",
                    "infoEmpty": "No hay registros disponibles",
                    "infoFiltered": "(filtrado de _MAX_ registros en total)",
                    "sSearch": "Buscar:",
                    "sProcessing":'Procesando...',
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sPrevious": "Anterior",
                        "sNext": "Siguiente",
                        "sLast": "Último"
                    }
                },
                "bSort": false,

            });
        });
    </script>
<% end %>

app/views/categories/new.html.erb
<%= render 'partials/content_header', back: true,backPath:categories_path ,title: @title,add:2,text:'',path_action: '' %>
<section class="content">
  <%= render 'form', category: @category %>
</section>

app/views/categories/show.html.erb
<%= render 'partials/content_header', back: true, backPath: categories_path, title: '', add: 0, text: '', path_action: @category, item: 'la categoría' %>
<section class="content">
  <div class="box">
    <div class="box-body">
      <div class="row form-horizontal">
        <div class="col-md-6">
          <div class="form-group">
            <div class="show-property">
              <label>
                <span class="show-key">Categoría:</span>
                <span class="show-value" >  <%= @category.name %></span>
              </label>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>